spring:
  application:
    name: Arquitetura Hexagonal - Ports and Adapters
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexagonal

hexagonal:
  client:
    address:
      url: http://localhost:8082/addresses
